"""Validation helpers for Excel artifacts generated by the automation."""

from __future__ import annotations

from pathlib import Path

import pandas as pd


class ArquivoVazioError(ValueError):
    """Raised when an empty dataframe or spreadsheet would be used as output."""


def garantir_dataframe_nao_vazio(dataframe: pd.DataFrame, contexto: str) -> None:
    if dataframe.empty:
        raise ArquivoVazioError(f"{contexto}: nenhum registro válido foi encontrado.")


def validar_arquivo_excel(caminho: Path, contexto: str) -> int:
    """Validate an existing non-empty Excel file and return its row count."""
    if not caminho.is_file():
        raise FileNotFoundError(f"{contexto}: arquivo não encontrado em {caminho}")
    if caminho.stat().st_size == 0:
        raise ArquivoVazioError(f"{contexto}: arquivo está vazio em {caminho}")

    if caminho.suffix.lower() not in {".xlsx", ".xls", ".csv"}:
        raise ValueError(f"{contexto}: extensão não suportada: {caminho.suffix}")
    try:
        dataframe = pd.read_csv(caminho) if caminho.suffix.lower() == ".csv" else pd.read_excel(caminho)
    except Exception as error:
        raise ValueError(f"{contexto}: arquivo não abre como planilha válida: {caminho}") from error
    garantir_dataframe_nao_vazio(dataframe, contexto)
    return len(dataframe)


def validar_arquivo_vendedores(caminho: Path) -> int:
    return validar_arquivo_excel(caminho, "Arquivo de vendedores")


def validar_arquivo_producao(caminho: Path) -> int:
    return validar_arquivo_excel(caminho, "Arquivo de produção")
